spring:
  datasource:
    url: jdbc:h2:mem:budgetr
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
